@startuml warmhouse-context-asis
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.14.0/C4_Context.puml

title диаграмма контекста as-is

Person(user, "пользователь", "владелец дома, включает и выключает отопление, смотрит температуру через веб-интерфейс")
Person(installer, "специалист по подключению", "выезжает к клиенту и подключает оборудование дома к системе")

System(smarthome, "умный дом", "монолит на go и postgresql, управление отоплением и мониторинг температуры")

System_Ext(heating, "система отопления дома", "реле отопления, установленное специалистом")
System_Ext(sensor, "датчик температуры", "удалённый датчик в доме, в репозитории эмулируется сервисом temperature-api")

Rel(user, smarthome, "управляет отоплением, смотрит температуру", "https, rest")
Rel(installer, heating, "устанавливает оборудование")
Rel(installer, smarthome, "заводит датчики дома", "https, rest")
Rel(smarthome, heating, "включает и выключает отопление", "http, синхронно")
Rel(smarthome, sensor, "запрашивает текущую температуру", "http, синхронно")
Rel_Back(smarthome, heating, "регистрируется при включении")

SHOW_LEGEND()
@enduml
